library("iml")
library("mlr3verse")
library("skimr")

set.seed(20211301)

# load dataset

load("south-german-credit.Rda")
data <- data[!(names(data) %in% c(
  "installment_rate",
  "present_residence", "number_credits"
))]
data <- droplevels.data.frame(data)
task <- TaskClassif$new("german-credit",
  backend = data, target = "credit_risk", positive = "good"
)

# 1 target, 20 features
# 18 factor features of which 3 are ordinal
# 3 numeric features (age, amount duration)
skimr::skim(task$data())


fencoder <- po("encode",
  method = "one-hot",
  affect_columns = selector_type("factor")
)
ord_to_int <- po("colapply",
  applicator = as.integer,
  affect_columns = selector_type("ordered")
)

# PipeOps
po_over <- po(
  "classbalancing",
  id = "oversample",
  adjust = "minor",
  reference = "minor",
  shuffle = FALSE,
  ratio = 2.3
)
pos <- po("scale") %>>%
  fencoder %>>% ord_to_int %>>% po_over

inner_cv5 <- rsmp("cv", folds = 5L)
measure <- msr("classif.bacc")
tuner <- mlr3tuning::tnr("grid_search", resolution = 7L)
terminator <- trm("evals", n_evals = 20)

radial_svm_learner <- lrn(
  "classif.svm",
  type = "C-classification",
  kernel = "radial",
  predict_type = "prob"
)
radial_svm_pipeline <-
  pos %>>% radial_svm_learner %>>% po("threshold")
radial_svm_glearner <-
  GraphLearner$new(radial_svm_pipeline, id = "radial_svm")
radial_svm_search_space <- ParamSet$new(list(
  ParamDbl$new("threshold.thresholds", lower = 0, upper = 1),
  ParamDbl$new("classif.svm.cost", lower = 0.01, upper = 100),
  ParamDbl$new("classif.svm.gamma", lower = 0.0001, upper = 1)
))
radial_svm_at <- AutoTuner$new(
  learner = radial_svm_glearner,
  resampling = inner_cv5,
  terminator = terminator,
  search_space = radial_svm_search_space,
  tuner = tuner,
  measure = measure
)

radial_svm_at$predict_type <- "prob"
radial_svm_at$train(task)

# hyperparameters
# radial_svm_at$model$tuning_instance$result
#    threshold.thresholds classif.svm.cost
# 1:            0.6666667              100
#    classif.svm.gamma learner_param_vals  x_domain
# 1:           0.16675         <list[14]> <list[3]>
#    classif.bacc
# 1:    0.6484142
radial_svm_at$model

data <- task$data()

x <- data

model <-
  Predictor$new(radial_svm_at, data = x, y = data$credit_risk)

victor <-
  data.frame(
    "age" = 24,
    "amount" = 4000,
    "credit_history" = "no credits taken/all credits paid back duly",
    "duration" = 60,
    "employment_duration" = "< 1 yr",
    "foreign_worker" = "yes",
    "housing" = "rent",
    "job" = "skilled employee/official",
    "other_debtors" = "none",
    "other_installment_plans" = "none",
    "people_liable" = "0 to 2",
    "personal_status_sex" = "female : non-single or male : single",
    "property" = "unknown / no property",
    "purpose" = "car (new)",
    "savings" = "... >= 1000 DM",
    "status" = "... >= 200 DM / salary for at least 1 year",
    "telephone" = "yes (under customer name)"
  )

# Shapley

# Making a prediction for victor
predict(radial_svm_at, victor)
model$predict(victor)
# [1] bad
# Levels: good bad
shapley <- Shapley$new(model, x.interest = victor)
plot(shapley)
# counterfactuals
devtools::load_all("counterfactuals", export_all = FALSE)
# generated by irace in folder appendix_irace
best_params <- readRDS("best_configs.rds")

cf <- Counterfactuals$new(
  predictor = model,
  x.interest = x[1, ],
  target = c(0.5, 1), epsilon = 0,
  generations = list(
    mosmafs::mosmafsTermStagnationHV(10),
    mosmafs::mosmafsTermGenerations(200)
  ),
  mu = best_params$mu,
  p.mut = best_params$p.mut, p.rec = best_params$p.rec,
  p.mut.gen = best_params$p.mut.gen,
  p.mut.use.orig = best_params$p.mut.use.orig,
  p.rec.gen = best_params$p.rec.gen, initialization = "icecurve",
  p.rec.use.orig = best_params$p.rec.use.orig,
)


# Anchors

# library("anchors")
# explainer <- anchors(task$data(), model, target = "credit_risk")
# explanations <- explain(task$data()[100, ], explainer)

# Tree surrogate
dt <- TreeSurrogate$new(model)
plot(dt)

# 2. Having no property should imply bad credit risk. ALE
effect <-
  FeatureEffects$new(model, features = c("property"), method = "ice")
plot(effect, features = c("property"))

# 4. Is there an interaction between job and credit_history ?
ia1 <- Interaction$new(model, feature = "job")
png("h-4.png")
plot(ia1)
dev.off()

# 8. Interaction property/age
ia2 <- Interaction$new(model, feature = "job")
png("h-8.png")
plot(ia2)
dev.off()
p <- ParamHelpers::makeParamSet(
  params = make_paramlist(rbind(model$data$get.x(), x.interest[model$data$feature.names]),
    lower = lower, upper = upper
  )
)
ParamHelpers::isFeasible(p, x.interest.list)
