---
title: "Interpretable Machine Learning Report"
author:
  - Xuan-Son Trinh^[Ludwig Maximilian University of Munich, Son.Trinh@campus.lmu.de]
  - Victor Tuekam^[Ludwig Maximilian University of Munich, t.victor@campus.lmu.de]
output: 
  bookdown::pdf_document2:
    citation_package: default
    toc: true
    toc_depth: 5
    pandoc_args: [ "--csl", "acm-sig-proceedings.csl" ]
bibliography: references.bib
biblio-style: ACM-Reference-Format-Journals
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, results='hide', warning=FALSE, error=FALSE, message=FALSE}
# Load necessary libraries
library(LinRegInteractive)
library(mlr3)
library(ggplot2)
```

# The dataset
The data set of our choice is Online News Popularity Data Set @online-news.
```{r, warning=FALSE}
data <- read.csv("datasets\\OnlineNewsPopularity\\OnlineNewsPopularity.csv", header = TRUE)
```

Start with some cleaning

```{r, warning=FALSE, message=FALSE, results='hide', warning=FALSE}
# Remove 2 non-predictive features + 1 uniformly distributed featyre  out of the dataset
data <- subset(data, select=-c(url, timedelta, n_non_stop_words))

#Converting categorical values from numeric to  factor - Weekdays
for (i in 32:38){
  data[,i] <- factor(data[,i])
  
}

#Converting categorical values from numeric to factor - News subjects
for (i in 14:19){
  data[,i] <- factor(data[,i])
}
```


\newpage

# References
