library("mlr3viz")
library("ggplot2")
library("mlr3verse")
set.seed(20211301)

devtools::load_all("../iml", export_all = FALSE)
devtools::load_all("../counterfactuals", export_all = FALSE)
# generated by irace in folder appendix_irace
best_params <- readRDS("../best_configs.rds")



load("./south-german-credit.Rda")

# counterfactuals

bob <-
  data.frame(
    "age" = 30,
    "amount" = 18424,
    "credit_history" = "no credits taken/all credits paid back duly",
    "duration" = 60, # 5 years
    "employment_duration" = "4 <= ... < 7 yrs",
    "foreign_worker" = "no",
    "housing" = "rent",
    "installment_rate" = "< 20",
    "job" = "manager/self-empl./highly qualif. employee",
    "number_credits" = "1",
    "other_debtors" = "none",
    "other_installment_plans" = "none",
    "people_liable" = "0 to 2",
    "personal_status_sex" = "male : married/widowed",
    "present_residence" = "1 <= ... < 4 yrs",
    "property" = "car or other",
    "purpose" = "business",
    "savings" = "... >= 1000 DM",
    "status" = "... >= 200 DM / salary for at least 1 year",
    "telephone" = "yes (under customer name)"
  )

james <-
  data.frame(
    "age" = 30,
    "amount" = 6480, # average car price in the 70s
    "credit_history" = "no credits taken/all credits paid back duly",
    "duration" = 12,
    "employment_duration" = "4 <= ... < 7 yrs",
    "foreign_worker" = "no",
    "housing" = "rent",
    "installment_rate" = "< 20",
    "job" = "skilled employee/official",
    "number_credits" = "2-3",
    "other_debtors" = "none",
    "other_installment_plans" = "bank",
    "people_liable" = "0 to 2",
    "personal_status_sex" = "female : non-single or male : single",
    "present_residence" = "< 1 yr",
    "property" = "unknown / no property",
    "purpose" = "car (new)",
    "savings" = "unknown/no savings account",
    "status" = "... >= 200 DM / salary for at least 1 year",
    "telephone" = "no"
  )
exclude <- c("installment_rate", "present_residence", "number_credits")
bob <- bob[!(names(x) %in% exclude)]
james <- james[!(names(x) %in% exclude)]
data <- data[!(names(data) %in% exclude)]

task <- TaskClassif$new("german-credit",
  backend = data, target = "credit_risk", positive = "good"
)


fencoder <- po("encode",
  method = "one-hot",
  affect_columns = selector_type("factor")
)
ord_to_int <- po("colapply",
  applicator = as.integer,
  affect_columns = selector_type("ordered")
)

# PipeOps
po_over <- po("classbalancing",
  id = "oversample", adjust = "minor",
  reference = "minor", shuffle = FALSE, ratio = 2.3
)
pos <- po("scale") %>>%
  fencoder %>>% ord_to_int %>>% po_over

inner_cv5 <- rsmp("cv", folds = 5L)
measure <- msr("classif.bacc")
tuner <- tnr("grid_search", resolution = 7L)
terminator <- trm("evals", n_evals = 20)

# Radial SVM
radial_svm_learner <- lrn("classif.svm",
  type = "C-classification", kernel = "radial", predict_type = "prob"
)
radial_svm_pipeline <- pos %>>% radial_svm_learner %>>% po("threshold")
radial_svm_glearner <- GraphLearner$new(radial_svm_pipeline, id = "radial_svm")
radial_svm_search_space <- ParamSet$new(list(
  ParamDbl$new("threshold.thresholds", lower = 0, upper = 1),
  ParamDbl$new("classif.svm.cost", lower = 0.01, upper = 100),
  ParamDbl$new("classif.svm.gamma", lower = 0.0001, upper = 1)
))

radial_svm_at <- AutoTuner$new(
  learner = radial_svm_glearner,
  resampling = inner_cv5,
  terminator = terminator,
  search_space = radial_svm_search_space,
  tuner = tuner,
  measure = measure
)

radial_svm_at$predict_type <- "prob"

radial_svm_at$train(task)

radial_svm_at$model


german <- as.data.frame(task$data())
x <- german[which(names(german) != "credit_risk")]
# x$age = as.integer(x$age)
model <- Predictor$new(radial_svm_at, data = x, y = german$credit_risk)

# effect = FeatureEffects$new(model)
# plot(effect, features = c("employment_duration"))
eff <- FeatureEffect$new(model, feature = c("employment_duration"))
eff$plot()

eff <- FeatureEffect$new(model, feature = c("employment_duration"), method = "pdp")
eff$plot()

eff <- FeatureEffect$new(model, feature = c("employment_duration"), method = "ice")
eff$plot()

eff$set.feature("installment_rate")
eff$plot()

# ggplot(data = data, mapping = aes(x = property, fill = credit_risk)) + geom_bar()


# Feature Importance
imp <- FeatureImp$new(model, loss = "f1")

# H-statistic Interaction
ia <- Interaction$new(model, feature = "job")

model$predict(victor)
model$predict(James)
shapley <- Shapley$new(model, x.interest = Bob)

cf <- Counterfactuals$new(
  predictor = model,
  x.interest = x[1, ],
  target = c(0.5, 1), epsilon = 0,
  generations = list(
    mosmafs::mosmafsTermStagnationHV(10),
    mosmafs::mosmafsTermGenerations(200)
  ),
  mu = best_params$mu,
  p.mut = best_params$p.mut, p.rec = best_params$p.rec,
  p.mut.gen = best_params$p.mut.gen,
  p.mut.use.orig = best_params$p.mut.use.orig,
  p.rec.gen = best_params$p.rec.gen, initialization = "icecurve",
  p.rec.use.orig = best_params$p.rec.use.orig,
)

a <- cf$plot_parallel(features = c("duration", "amount"), plot.x.interest = FALSE)
a <- a + scale_x_discrete(expand = c(0.1, 0.1), labels = c("duration", "credit amount"))
a
b <- cf$plot_surface(features = c("duration", "amount"))
b
c <- cf$plot_hv()
c
